<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Curso JavaScript</title>
</head>

<body>
  <h1>Fundamentos JavaScript</h1>
  <script>
    //MANEJO DE ERRORES TRY CATCH, FINALLY
    try {
      console.log("En el try se agrega el codigo a evaluar");
      NoExiste;
    } catch (error) {
      console.log("Catch captura cualquie error surgido o lanzado en el try");
      console.log(error);
    } finally {
      console.log("el bloque finally se ejecutara siempre al final de un bloque try catch");
    }

    try {
      let numero = "y";
      if (isNaN(numero)) {//la funcion NaN not a number evalua si la variable es un numero o no si si no es arroja un false
        throw new Error("El caracter introducido no es un numero");//throw lanza un neuvo mensaje Error es un metodo
      }
      console.log(numero * numero);
    } catch (error) {
      console.log(`se produjo el siguiente error: ${error}`);
    }
  </script>
</body>

</html>